[package]
name = "chal11"
version = "0.1.0"
authors = ["tdeslauriers <thomas.deslauriers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.3"
base64 = "0.13.0"
openssl = "0.10.30"